<p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25441a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos/BeeJh5lz3k6kSIzA</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25441070>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos/BeeJh5lz3k6kSIzA</p><p><b>[WARN]</b>&nbsp;Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25441190>: Failed to establish a new connection: [Errno 111] Connection refused')': /produtos/BeeJh5lz3k6kSIzA</p><p style="color: red"><b>[FAIL]</b>&nbsp;ConnectionError: HTTPConnectionPool(host='localhost', port=3030): Max retries exceeded with url: /produtos/BeeJh5lz3k6kSIzA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f25441700>: Failed to establish a new connection: [Errno 111] Connection refused'))</p>